service: aws-be-nexgenua

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true

functions:
  getProducts:
    handler: handler.getProducts
    events:
      - http:
          path: products
          method: get
          cors: true

  getProductById:
    handler: handler.getProductById
    events:
      - http:
          path: products/{id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                productId: true
